apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-mongo-example-helm.fullname" . }}-db-configmap
  labels:
  {{- include "flask-mongo-example-helm.labels" . | nindent 4 }}
data:
  database_url: {{ .Values.dbConfigmap.databaseUrl | quote }}