apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-mongo-example-helm.fullname" . }}-db-secret
  labels:
  {{- include "flask-mongo-example-helm.labels" . | nindent 4 }}
data:
  mongo-root-password: {{ required "dbSecret.mongoRootPassword is required" .Values.dbSecret.mongoRootPassword
    | b64enc | quote }}
  mongo-root-username: {{ required "dbSecret.mongoRootUsername is required" .Values.dbSecret.mongoRootUsername
    | b64enc | quote }}
type: Opaque