apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-mongo-example-helm.fullname" . }}-db-service
  labels:
  {{- include "flask-mongo-example-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbService.type }}
  selector:
    app: mongodb
  {{- include "flask-mongo-example-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.dbService.ports | toYaml | nindent 2 -}}