apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-deployment
  template:
    metadata:
      labels:
        app: flask-app-deployment
    spec:
      containers:
      - name: flask-app-deployment
        image: bdor528/flask-kubernetes:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app-service
# spec:
#   selector:
#     app: flask-app-deployment
#   ports:
#   - protocol: TCP
#     port: 5000
#     targetPort: 5000
#     nodePort: 30001
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: my-namespace
spec:
  selector:
    app: flask-app-deployment
  type: ClusterIP
  ports:
    - name: http
      targetPort: 5000
      port: 5000
